title: Elastic Common Schema mapping for proxy logs
order: 20
backends:
  - es-qs
  - es-dsl
  - es-rule
  - kibana
  - xpack-watcher
  - elastalert
  - elastalert-dsl
logsources:
  proxy:
    category: proxy
    index: filebeat-*
fieldmappings:
  c-uri: url.original
  c-uri-extension: url.extension
  c-uri-query: url.query
  c-uri-stem: url.original
  c-useragent: user_agent.original
  cs-bytes: http.request.body.bytes
  cs-cookie: http.cookie
  cs-host: url.domain
  cs-method: http.request.method
  cs-referrer: http.request.referrer
  cs-version: http.version
  r-dns: url.domain
  sc-status: http.response.status_code
  sc-bytes: http.response.body.bytes
